theme: jekyll-theme-minimal
title: Dylan Labatt Randle
description: A personal website
logo: pics/R.png
github: [metadata]
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
