theme: jekyll-theme-minimal
title: Dylan Labatt Randle
description: Personal Website
logo: pics/dylan-red2.jpg
github: [metadata]
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
