title: Dylan Randle
description: Copyright © 2022. All rights reserved.

theme: minima

markdown: kramdown
kramdown:
  math_engine: mathjax

github: [metadata]

header_pages:
  - index.md
  - blog/blog.md
  - notes/notes.md
