theme: jekyll-theme-primer
title: Dylan Labatt Randle
description: Website containing personal information and projects
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
