theme: minima
title: Dylan Randle
description: Copyright © 2022. All rights reserved.
github: [metadata]
markdown: kramdown
kramdown:
    math_engine: mathjax
header_pages:
  - index.md
  - blog/blog.md
  - notes/notes.md
