theme: minima
title: Dylan Labatt Randle
description: Copyright © 2018 Dylan Labatt Randle. All rights reserved.
logo: pics/R.png
github: [metadata]
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
header_pages:
  - index.md
  - research.md
  - applied.md
  - blog.md
