theme: jekyll-theme-primer
title: Dylan Randle Homepage
description: Starting point for all things Dylan
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
