theme: minima
title: Dylan Randle
description: Copyright © 2021. All rights reserved.
logo: pics/R.png
github: [metadata]
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
header_pages:
  - index.md
  - projects.md
  - recognition.md
  - blog.md
